OXID-64_split_export
findologic/plugin-oxid-di pull request #1
Opened 2020-08-18 09:49 UTC by TheKeymaster

2020-09-08 15:10 UTC, dblaichinger requested changes

2020-09-08 15:10 UTC, dblaichinger commented on findologic/findologic/Controller/Findologic.php
> +            // TODO: The export plugin should be available at docs.findologic.com.
Add link when export plugin has been uploaded

2020-09-08 15:10 UTC, dblaichinger commented on findologic/findologic/Controller/Findologic.php
> +        include_once __DIR__ . '/../../../findologic-export/findologic-export/FindologicExport.php';
I don't like the double findologic-export

2020-09-08 15:10 UTC, dblaichinger commented on findologic/findologic/findologic_export.php
> +// COPY THIS FILE TO THE "source" FOLDER OF YOUR OXID INSTANCE
Why is this manual step necessary?

2020-09-09 09:30 UTC, TheKeymaster commented on findologic/findologic/Controller/Findologic.php
> +        include_once __DIR__ . '/../../../findologic-export/findologic-export/FindologicExport.php';
It can be anything, but it should be unique. Therefore `findologic` was not possible, since we already have a plugin with the name `findologic`.

2020-09-09 09:31 UTC, TheKeymaster commented on findologic/findologic/findologic_export.php
> +// COPY THIS FILE TO THE "source" FOLDER OF YOUR OXID INSTANCE
Because it always has been. This was not changed.

2020-09-09 09:33 UTC, dblaichinger commented on findologic/findologic/Controller/Findologic.php
> +        include_once __DIR__ . '/../../../findologic-export/findologic-export/FindologicExport.php';
`'/../../../findologic-export/FindologicExport.php'`?

2020-09-28 17:27 UTC, dblaichinger commented on findologic/findologic/Controller/Findologic.php
> +        include_once __DIR__ . '/../../../findologic-export/findologic-export/FindologicExport.php';
As stated by Dom, not possible it needs to be separate folders

2020-09-30 12:40 UTC, merged